/// <reference types="vite/client" />

// Third-party packages without bundled type declarations.
declare module 'jsvectormap'
declare module 'jsvectormap/dist/maps/world.js'

// Page index generated by the pagesIndex plugin in vite.config.js.
declare module 'virtual:pages' {
  export const pages: { path: string; title: string }[]
}
